### ISSUE TITLE
swipedelete example crashes

### ISSUE THREAD

**Issue by projekt01** [kivy-garden/garden.swipetodelete#1]
The sample crashes on a windows system wiht kivy 1.9.0. I don't know how to debug the animation in the loop and find the missing reference which is None.

Here is a traceback:

[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "D:\svnXeebo\packages\trunk\xmobile2\bin\sample-script.py", line 18, in <module>
     sys.exit(xmobile.sample.main())
   File "d:\svnxeebo\packages\trunk\xmobile2\src\xmobile\sample.py", line 386, in main
     app.run()
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\app.py", line 824, in run
     runTouchApp()
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\core\window\window_sdl2.py", line 525, in mainloop
     self._mainloop()
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\core\window\window_sdl2.py", line 290, in _mainloop
     EventLoop.idle()
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\base.py", line 327, in idle
     Clock.tick()
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\clock.py", line 483, in tick
     self._process_events()
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\clock.py", line 615, in _process_events
     event.tick(self._last_tick, remove)
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\clock.py", line 374, in tick
     ret = callback(self._dt)
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\animation.py", line 335, in _update
     value = calculate(a, b, t)
   File "D:\svnXeebo\packages\trunk\xmobile2\kivy\kivy27\kivy\animation.py", line 363, in _calculate
     return (a \* (1. - t)) + (b \* t)
 TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Regards
Roger Ineichen

**Comment by kiok46** [comment]
@projekt01  Thank you for mentioning this, I will fix this soon :)

**Comment by kiok46** [comment]
Hi @projekt01  This issue is solved, If it occurs again then please reopen.
